version: "3.9"

services:
  db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:7.1
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yardzen.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - "5050:80"
